const { withMainActivity } = require("@expo/config-plugins");

const IMPORT_LINE = "import dev.matinzd.healthconnect.permissions.HealthConnectPermissionDelegate";
const DELEGATE_CALL = "    HealthConnectPermissionDelegate.setPermissionDelegate(this)";

// react-native-health-connect declares setPermissionDelegate but never calls it anywhere in the
// library, so the host app has to. Without it requestPermission() dies with
// UninitializedPropertyAccessException on the delegate's lateinit ActivityResultLauncher.
//
// It has to go in onCreate: registerForActivityResult must run before the activity reaches
// STARTED. And it has to be a config plugin rather than a hand edit, because MainActivity.kt is
// regenerated by every prebuild.
const withHealthConnectPermissionDelegate = (config) =>
  withMainActivity(config, (config) => {
    let contents = config.modResults.contents;

    if (!contents.includes(IMPORT_LINE)) {
      contents = contents.replace(
        "import expo.modules.ReactActivityDelegateWrapper",
        `import expo.modules.ReactActivityDelegateWrapper\n\n${IMPORT_LINE}`
      );
    }

    if (!contents.includes("setPermissionDelegate")) {
      contents = contents.replace("    super.onCreate(null)", `    super.onCreate(null)\n${DELEGATE_CALL}`);
    }

    config.modResults.contents = contents;
    return config;
  });

module.exports = withHealthConnectPermissionDelegate;
